<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
<head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Unit Test Results: All Tests</title>
<link rel="stylesheet" type="text/css" title="Style" href="stylesheet.css">
</head>
<body onload="open('allclasses-frame.html','classListFrame')">
<h1>Unit Test Results.</h1>
<table width="100%">
<tr>
<td align="left"></td><td align="right">Designed for use with <a href="http://www.junit.org/">JUnit</a> and <a href="http://ant.apache.org/">Ant</a>.</td>
</tr>
</table>
<hr size="1">
<h2>All Tests</h2>
<table class="details" border="0" cellpadding="5" cellspacing="2" width="95%">
<tr valign="top">
<th>Class</th><th>Name</th><th>Status</th><th width="80%">Type</th><th nowrap>Time(s)</th>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testCrearRol"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testCrearRol">testCrearRol</a></td><td>Error</td><td>org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.roles' doesn't exist"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.roles' doesn't exist"<br>	at edu.uag.iidis.scec.persistencia.RolDAO.hazPersistente(RolDAO.java:118)<br>	at edu.uag.iidis.scec.pruebas.RolDAOTest.testCrearRol(RolDAOTest.java:37)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.roles' doesn't exist"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:100)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeQuery(Unknown Source)<br>	at org.hibernate.id.IncrementGenerator.initializePreviousValueHolder(IncrementGenerator.java:128)<br>	at org.hibernate.id.IncrementGenerator.generate(IncrementGenerator.java:68)<br>	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:120)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:204)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:189)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:114)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)<br>	at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:615)<br>	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:608)<br>	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:604)<br>	at edu.uag.iidis.scec.persistencia.RolDAO.hazPersistente(RolDAO.java:113)<br>Caused by: java.sql.SQLException: Base table or view not found,  message from server: "Table 'manto.roles' doesn't exist"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1555)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.156</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testCrearUsuario"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testCrearUsuario">testCrearUsuario</a></td><td>Error</td><td>org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at edu.uag.iidis.scec.persistencia.UsuarioDAO.hazPersistente(UsuarioDAO.java:198)<br>	at edu.uag.iidis.scec.pruebas.UsuarioDAOTest.testCrearUsuario(UsuarioDAOTest.java:41)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:100)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeQuery(Unknown Source)<br>	at org.hibernate.id.IncrementGenerator.initializePreviousValueHolder(IncrementGenerator.java:128)<br>	at org.hibernate.id.IncrementGenerator.generate(IncrementGenerator.java:68)<br>	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:120)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:204)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:189)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:114)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)<br>	at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:615)<br>	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:608)<br>	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:604)<br>	at edu.uag.iidis.scec.persistencia.UsuarioDAO.hazPersistente(UsuarioDAO.java:192)<br>Caused by: java.sql.SQLException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1555)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.000</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testBuscarTodos"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testBuscarTodos">testBuscarTodos</a></td><td>Error</td><td>org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at edu.uag.iidis.scec.persistencia.UsuarioDAO.buscarTodos(UsuarioDAO.java:111)<br>	at edu.uag.iidis.scec.pruebas.UsuarioDAOTest.testBuscarTodos(UsuarioDAOTest.java:116)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:100)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeQuery(Unknown Source)<br>	at org.hibernate.loader.Loader.getResultSet(Loader.java:1978)<br>	at org.hibernate.loader.Loader.doQuery(Loader.java:829)<br>	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)<br>	at org.hibernate.loader.Loader.doList(Loader.java:2463)<br>	at org.hibernate.loader.Loader.doList(Loader.java:2449)<br>	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2279)<br>	at org.hibernate.loader.Loader.list(Loader.java:2274)<br>	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:122)<br>	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1483)<br>	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:374)<br>	at edu.uag.iidis.scec.persistencia.UsuarioDAO.buscarTodos(UsuarioDAO.java:106)<br>Caused by: java.sql.SQLException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1555)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.016</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testAgregarRol"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testAgregarRol">testAgregarRol</a></td><td>Error</td><td>Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>
<br>
<code>org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:100)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeQuery(Unknown Source)<br>	at org.hibernate.loader.Loader.getResultSet(Loader.java:1978)<br>	at org.hibernate.loader.Loader.doQuery(Loader.java:829)<br>	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)<br>	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)<br>	at org.hibernate.loader.Loader.loadEntity(Loader.java:2058)<br>	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82)<br>	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3697)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:439)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:420)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:204)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:143)<br>	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)<br>	at org.hibernate.internal.SessionImpl.immediateLoad(SessionImpl.java:891)<br>	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:158)<br>	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:195)<br>	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:185)<br>	at edu.uag.iidis.scec.modelo.Usuario_$$_javassist_6.addRol(Usuario_$$_javassist_6.java)<br>	at edu.uag.iidis.scec.pruebas.UsuarioDAOTest.testAgregarRol(UsuarioDAOTest.java:133)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: java.sql.SQLException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1555)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.016</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testVerificarRol"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testVerificarRol">testVerificarRol</a></td><td>Error</td><td>Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>
<br>
<code>org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:100)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeQuery(Unknown Source)<br>	at org.hibernate.loader.Loader.getResultSet(Loader.java:1978)<br>	at org.hibernate.loader.Loader.doQuery(Loader.java:829)<br>	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)<br>	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)<br>	at org.hibernate.loader.Loader.loadEntity(Loader.java:2058)<br>	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82)<br>	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3697)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:439)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:420)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:204)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:143)<br>	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)<br>	at org.hibernate.internal.SessionImpl.immediateLoad(SessionImpl.java:891)<br>	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:158)<br>	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:195)<br>	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:185)<br>	at edu.uag.iidis.scec.modelo.Usuario_$$_javassist_6.getRoles(Usuario_$$_javassist_6.java)<br>	at edu.uag.iidis.scec.pruebas.UsuarioDAOTest.testVerificarRol(UsuarioDAOTest.java:151)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: java.sql.SQLException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1555)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.000</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testEliminarRol"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testEliminarRol">testEliminarRol</a></td><td>Error</td><td>Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>
<br>
<code>org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:100)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeQuery(Unknown Source)<br>	at org.hibernate.loader.Loader.getResultSet(Loader.java:1978)<br>	at org.hibernate.loader.Loader.doQuery(Loader.java:829)<br>	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)<br>	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)<br>	at org.hibernate.loader.Loader.loadEntity(Loader.java:2058)<br>	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82)<br>	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3697)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:439)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:420)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:204)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:143)<br>	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)<br>	at org.hibernate.internal.SessionImpl.immediateLoad(SessionImpl.java:891)<br>	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:158)<br>	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:195)<br>	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:185)<br>	at edu.uag.iidis.scec.modelo.Usuario_$$_javassist_6.removeRol(Usuario_$$_javassist_6.java)<br>	at edu.uag.iidis.scec.pruebas.UsuarioDAOTest.testEliminarRol(UsuarioDAOTest.java:166)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: java.sql.SQLException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1555)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.015</td>
</tr>
<tr valign="top" class="TableRowColor">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testCrearUsuarioInvalido"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testCrearUsuarioInvalido">testCrearUsuarioInvalido</a></td><td>Success</td><td></td><td>0.000</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testBuscarUsuarioPorId"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testBuscarUsuarioPorId">testBuscarUsuarioPorId</a></td><td>Error</td><td>Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>
<br>
<code>org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:100)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeQuery(Unknown Source)<br>	at org.hibernate.loader.Loader.getResultSet(Loader.java:1978)<br>	at org.hibernate.loader.Loader.doQuery(Loader.java:829)<br>	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)<br>	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)<br>	at org.hibernate.loader.Loader.loadEntity(Loader.java:2058)<br>	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82)<br>	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3697)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:439)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:420)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:204)<br>	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:143)<br>	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:954)<br>	at org.hibernate.internal.SessionImpl.immediateLoad(SessionImpl.java:891)<br>	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:158)<br>	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:195)<br>	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:185)<br>	at edu.uag.iidis.scec.modelo.Usuario_$$_javassist_6.getNombre(Usuario_$$_javassist_6.java)<br>	at edu.uag.iidis.scec.pruebas.UsuarioDAOTest.testBuscarUsuarioPorId(UsuarioDAOTest.java:85)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: java.sql.SQLException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1555)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.000</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html">AllTests</a></td><td><a name="testBuscarPorEjemplo"></a><a href="edu/uag/iidis/scec/pruebas/0_AllTests.html#testBuscarPorEjemplo">testBuscarPorEjemplo</a></td><td>Error</td><td>org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at edu.uag.iidis.scec.persistencia.UsuarioDAO.buscarPorEjemplo(UsuarioDAO.java:135)<br>	at edu.uag.iidis.scec.pruebas.UsuarioDAOTest.testBuscarPorEjemplo(UsuarioDAOTest.java:102)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:100)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeQuery(Unknown Source)<br>	at org.hibernate.loader.Loader.getResultSet(Loader.java:1978)<br>	at org.hibernate.loader.Loader.doQuery(Loader.java:829)<br>	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)<br>	at org.hibernate.loader.Loader.doList(Loader.java:2463)<br>	at org.hibernate.loader.Loader.doList(Loader.java:2449)<br>	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2279)<br>	at org.hibernate.loader.Loader.list(Loader.java:2274)<br>	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:122)<br>	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1483)<br>	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:374)<br>	at edu.uag.iidis.scec.persistencia.UsuarioDAO.buscarPorEjemplo(UsuarioDAO.java:130)<br>Caused by: java.sql.SQLException: Base table or view not found,  message from server: "Table 'manto.usuarios' doesn't exist"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1555)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.016</td>
</tr>
<<<<<<< HEAD
<tr valign="top" class="TableRowColor">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testBuscarTodosE"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testBuscarTodosE">testBuscarTodosE</a></td><td>Success</td><td></td><td>6.370</td>
=======
<<<<<<< HEAD
<tr valign="top" class="TableRowColor">
<<<<<<< HEAD
<td><a href="edu/uag/iidis/scec/pruebas/1_EventoDAOTest.html">EventoDAOTest</a></td><td><a name="testActulizarEvento"></a><a href="edu/uag/iidis/scec/pruebas/1_EventoDAOTest.html#testActulizarEvento">testActulizarEvento</a></td><td>Success</td><td></td><td>0.000</td>
</tr>
<tr valign="top" class="Failure">
<td><a href="edu/uag/iidis/scec/pruebas/1_EventoDAOTest.html">EventoDAOTest</a></td><td><a name="testCrearEvento"></a><a href="edu/uag/iidis/scec/pruebas/1_EventoDAOTest.html#testCrearEvento">testCrearEvento</a></td><td>Failure</td><td>N/A<br>
<br>
<code>junit.framework.AssertionFailedError<br>	at edu.uag.iidis.scec.pruebas.EventoDAOTest.testCrearEvento(EventoDAOTest.java:32)<br>
</code></td><td>0.130</td>
</tr>
<tr valign="top" class="Error">
=======
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testCrearPerfilE"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testCrearPerfilE">testCrearPerfilE</a></td><td>Success</td><td></td><td>1.676</td>
=======
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testCrearPerfilE"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testCrearPerfilE">testCrearPerfilE</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate entry 'joss' for key 'usuario'<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate entry 'joss' for key 'usuario'<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:259)<br>	at edu.uag.iidis.scec.pruebas.PerfilDAOTest.testCrearPerfilE(PerfilDAOTest.java:26)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate entry 'joss' for key 'usuario'<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy5.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:250)<br>Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'joss' for key 'usuario'<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)<br>	at com.mysql.jdbc.Util.getInstance(Util.java:408)<br>	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)<br>	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)<br>	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)<br>	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>6.484</td>
>>>>>>> 0705102ddd72b9af999ae3f3b5073ebc442cbf60
>>>>>>> 84e4b401d0acfb3afd506f251a3dc8343e3c423e
</tr>
<tr valign="top" class="Failure">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testBuscarTodosF"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testBuscarTodosF">testBuscarTodosF</a></td><td>Failure</td><td>Existen datos<br>
<br>
<code>junit.framework.AssertionFailedError: Existen datos<br>	at edu.uag.iidis.scec.pruebas.PerfilDAOTest.testBuscarTodosF(PerfilDAOTest.java:138)<br>
</code></td><td>0.031</td>
</tr>
<tr valign="top" class="TableRowColor">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testCrearPerfilE"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testCrearPerfilE">testCrearPerfilE</a></td><td>Success</td><td></td><td>0.531</td>
</tr>
<tr valign="top" class="Failure">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testCrearPerfilF"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testCrearPerfilF">testCrearPerfilF</a></td><td>Failure</td><td>Usuario ya existe<br>
<br>
<code>junit.framework.AssertionFailedError: Usuario ya existe<br>	at edu.uag.iidis.scec.pruebas.PerfilDAOTest.testCrearPerfilF(PerfilDAOTest.java:56)<br>
</code></td><td>0.172</td>
</tr>
<tr valign="top" class="TableRowColor">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testEliminarPerfilE"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testEliminarPerfilE">testEliminarPerfilE</a></td><td>Success</td><td></td><td>0.110</td>
</tr>
<tr valign="top" class="Failure">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testEliminarPerfilF"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testEliminarPerfilF">testEliminarPerfilF</a></td><td>Failure</td><td>No se encontro el dato a eliminar<br>
<br>
<code>junit.framework.AssertionFailedError: No se encontro el dato a eliminar<br>	at edu.uag.iidis.scec.pruebas.PerfilDAOTest.testEliminarPerfilF(PerfilDAOTest.java:225)<br>
</code></td><td>0.015</td>
</tr>
<tr valign="top" class="TableRowColor">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testExistePerfilE"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testExistePerfilE">testExistePerfilE</a></td><td>Success</td><td></td><td>0.000</td>
</tr>
<tr valign="top" class="Failure">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testExistePerflF"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testExistePerflF">testExistePerflF</a></td><td>Failure</td><td>El perfil no existe<br>
<br>
<code>junit.framework.AssertionFailedError: El perfil no existe<br>	at edu.uag.iidis.scec.pruebas.PerfilDAOTest.testExistePerflF(PerfilDAOTest.java:177)<br>
</code></td><td>0.016</td>
</tr>
<tr valign="top" class="TableRowColor">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testOrdenarPerfilesPorE"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testOrdenarPerfilesPorE">testOrdenarPerfilesPorE</a></td><td>Success</td><td></td><td>0.078</td>
</tr>
<tr valign="top" class="Failure">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testOrdenarPerfilesPorF"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testOrdenarPerfilesPorF">testOrdenarPerfilesPorF</a></td><td>Failure</td><td>Los datos no se pudieron ordenar<br>
<br>
<code>junit.framework.AssertionFailedError: Los datos no se pudieron ordenar<br>	at edu.uag.iidis.scec.pruebas.PerfilDAOTest.testOrdenarPerfilesPorF(PerfilDAOTest.java:268)<br>
</code></td><td>0.016</td>
</tr>
<tr valign="top" class="TableRowColor">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testUpdatePerfilE"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testUpdatePerfilE">testUpdatePerfilE</a></td><td>Success</td><td></td><td>0.046</td>
</tr>
<tr valign="top" class="Failure">
<td><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html">PerfilDAOTest</a></td><td><a name="testUpdatePerfilF"></a><a href="edu/uag/iidis/scec/pruebas/1_PerfilDAOTest.html#testUpdatePerfilF">testUpdatePerfilF</a></td><td>Failure</td><td>No se pudieron actualizar los datos<br>
<br>
<code>junit.framework.AssertionFailedError: No se pudieron actualizar los datos<br>	at edu.uag.iidis.scec.pruebas.PerfilDAOTest.testUpdatePerfilF(PerfilDAOTest.java:99)<br>
</code></td><td>0.016</td>
</tr>
<tr valign="top" class="Error">
>>>>>>> 43e17c3d83292f04fe3b4937ee7f12a705823dfe
<td><a href="edu/uag/iidis/scec/pruebas/2_RolDAOTest.html">RolDAOTest</a></td><td><a name="testCrearRol"></a><a href="edu/uag/iidis/scec/pruebas/2_RolDAOTest.html#testCrearRol">testCrearRol</a></td><td>Error</td><td>org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.roles' doesn't exist"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.roles' doesn't exist"<br>	at edu.uag.iidis.scec.persistencia.RolDAO.hazPersistente(RolDAO.java:118)<br>	at edu.uag.iidis.scec.pruebas.RolDAOTest.testCrearRol(RolDAOTest.java:37)<br>	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)<br>	at junit.extensions.TestSetup$1.protect(TestSetup.java:19)<br>	at junit.extensions.TestSetup.run(TestSetup.java:23)<br>Caused by: org.hibernate.exception.SQLGrammarException: Base table or view not found,  message from server: "Table 'manto.roles' doesn't exist"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:100)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy3.executeQuery(Unknown Source)<br>	at org.hibernate.id.IncrementGenerator.initializePreviousValueHolder(IncrementGenerator.java:128)<br>	at org.hibernate.id.IncrementGenerator.generate(IncrementGenerator.java:68)<br>	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:120)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:204)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:189)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:114)<br>	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)<br>	at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:615)<br>	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:608)<br>	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:604)<br>	at edu.uag.iidis.scec.persistencia.RolDAO.hazPersistente(RolDAO.java:113)<br>Caused by: java.sql.SQLException: Base table or view not found,  message from server: "Table 'manto.roles' doesn't exist"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1555)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.156</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html">VehiculoDAOTest</a></td><td><a name="testCrearVehiculoE"></a><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html#testCrearVehiculoE">testCrearVehiculoE</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'AHI98G' for key 'placa_UNIQUE'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'AHI98G' for key 'placa_UNIQUE'"<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:275)<br>	at edu.uag.iidis.scec.pruebas.VehiculoDAOTest.testCrearVehiculoE(VehiculoDAOTest.java:26)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'AHI98G' for key 'placa_UNIQUE'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy5.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:266)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'AHI98G' for key 'placa_UNIQUE'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>1.744</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html">VehiculoDAOTest</a></td><td><a name="testCrearVehiculoF"></a><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html#testCrearVehiculoF">testCrearVehiculoF</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'AHI98G' for key 'placa_UNIQUE'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'AHI98G' for key 'placa_UNIQUE'"<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:275)<br>	at edu.uag.iidis.scec.pruebas.VehiculoDAOTest.testCrearVehiculoF(VehiculoDAOTest.java:47)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'AHI98G' for key 'placa_UNIQUE'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy5.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)<br>	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1081)<br>	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:315)<br>	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)<br>	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)<br>	at edu.uag.iidis.scec.persistencia.hibernate.HibernateUtil.commitTransaction(HibernateUtil.java:266)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'AHI98G' for key 'placa_UNIQUE'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.008</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html">VehiculoDAOTest</a></td><td><a name="test4ActualizarVehiculoF"></a><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html#test4ActualizarVehiculoF">test4ActualizarVehiculoF</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.NullPointerException<br>	at edu.uag.iidis.scec.persistencia.VehiculoDAO.hazPersistenteP(VehiculoDAO.java:131)<br>	at edu.uag.iidis.scec.pruebas.VehiculoDAOTest.test4ActualizarVehiculoF(VehiculoDAOTest.java:86)<br>
</code></td><td>0.124</td>
</tr>
<tr valign="top" class="TableRowColor">
<td><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html">VehiculoDAOTest</a></td><td><a name="testActualizarVehiculo"></a><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html#testActualizarVehiculo">testActualizarVehiculo</a></td><td>Success</td><td></td><td>0.018</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html">VehiculoDAOTest</a></td><td><a name="testEliminarVehiculo"></a><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html#testEliminarVehiculo">testEliminarVehiculo</a></td><td>Error</td><td>attempt to create delete event with null entity<br>
<br>
<code>java.lang.IllegalArgumentException: attempt to create delete event with null entity<br>	at org.hibernate.event.spi.DeleteEvent.&lt;init&gt;(DeleteEvent.java:45)<br>	at org.hibernate.internal.SessionImpl.delete(SessionImpl.java:801)<br>	at edu.uag.iidis.scec.persistencia.VehiculoDAO.hazTransitorio(VehiculoDAO.java:163)<br>	at edu.uag.iidis.scec.pruebas.VehiculoDAOTest.testEliminarVehiculo(VehiculoDAOTest.java:169)<br>
</code></td><td>0.005</td>
</tr>
<tr valign="top" class="TableRowColor">
<<<<<<< HEAD
<td><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html">VehiculoDAOTest</a></td><td><a name="testCrearVehiculo"></a><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html#testCrearVehiculo">testCrearVehiculo</a></td><td>Success</td><td></td><td>4.838</td>
=======
<td><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html">VehiculoDAOTest</a></td><td><a name="testBuscarTodos"></a><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html#testBuscarTodos">testBuscarTodos</a></td><td>Success</td><td></td><td>0.068</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html">VehiculoDAOTest</a></td><td><a name="ordenarVehiculosPor"></a><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html#ordenarVehiculosPor">ordenarVehiculosPor</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'OIUP2U3' for key 'placa_UNIQUE'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'OIUP2U3' for key 'placa_UNIQUE'"<br>	at edu.uag.iidis.scec.persistencia.VehiculoDAO.ordenarVehiculosPor(VehiculoDAO.java:364)<br>	at edu.uag.iidis.scec.pruebas.VehiculoDAOTest.ordenarVehiculosPor(VehiculoDAOTest.java:190)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'OIUP2U3' for key 'placa_UNIQUE'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy5.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:59)<br>	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1053)<br>	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1108)<br>	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)<br>	at edu.uag.iidis.scec.persistencia.VehiculoDAO.ordenarVehiculosPor(VehiculoDAO.java:349)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'OIUP2U3' for key 'placa_UNIQUE'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.010</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html">VehiculoDAOTest</a></td><td><a name="testExisteVehiculoE"></a><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html#testExisteVehiculoE">testExisteVehiculoE</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'QWER82' for key 'placa_UNIQUE'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'QWER82' for key 'placa_UNIQUE'"<br>	at edu.uag.iidis.scec.persistencia.VehiculoDAO.existeVehiculo(VehiculoDAO.java:220)<br>	at edu.uag.iidis.scec.pruebas.VehiculoDAOTest.testExisteVehiculoE(VehiculoDAOTest.java:129)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'QWER82' for key 'placa_UNIQUE'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy5.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:59)<br>	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1053)<br>	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1108)<br>	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)<br>	at edu.uag.iidis.scec.persistencia.VehiculoDAO.existeVehiculo(VehiculoDAO.java:205)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'QWER82' for key 'placa_UNIQUE'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.015</td>
</tr>
<tr valign="top" class="Error">
<td><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html">VehiculoDAOTest</a></td><td><a name="testExisteVehiculoF"></a><a href="edu/uag/iidis/scec/pruebas/3_VehiculoDAOTest.html#testExisteVehiculoF">testExisteVehiculoF</a></td><td>Error</td><td>org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'QWER82' for key 'placa_UNIQUE'"<br>
<br>
<code>edu.uag.iidis.scec.excepciones.ExcepcionInfraestructura: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'QWER82' for key 'placa_UNIQUE'"<br>	at edu.uag.iidis.scec.persistencia.VehiculoDAO.existeVehiculo(VehiculoDAO.java:220)<br>	at edu.uag.iidis.scec.pruebas.VehiculoDAOTest.testExisteVehiculoF(VehiculoDAOTest.java:150)<br>Caused by: org.hibernate.exception.ConstraintViolationException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'QWER82' for key 'placa_UNIQUE'"<br>	at org.hibernate.exception.internal.SQLStateConverter.convert(SQLStateConverter.java:104)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)<br>	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)<br>	at com.sun.proxy.$Proxy5.executeUpdate(Unknown Source)<br>	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:56)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2849)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3290)<br>	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:80)<br>	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:273)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:265)<br>	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:186)<br>	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:323)<br>	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:59)<br>	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1053)<br>	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1108)<br>	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)<br>	at edu.uag.iidis.scec.persistencia.VehiculoDAO.existeVehiculo(VehiculoDAO.java:205)<br>Caused by: java.sql.SQLException: Duplicate key or integrity constraint violation,  message from server: "Duplicate entry 'QWER82' for key 'placa_UNIQUE'"<br>	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1977)<br>	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1163)<br>	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1272)<br>	at com.mysql.jdbc.Connection.execSQL(Connection.java:2236)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1741)<br>	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1588)<br>	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)<br>
</code></td><td>0.014</td>
>>>>>>> 43e17c3d83292f04fe3b4937ee7f12a705823dfe
</tr>
</table>
</body>
</html>
